language: node_js
install: npm install
sudo: required
addons:
  chrome: stable
node_js:
  - "node"
script:
  - npm test
  - CHROME_HEADLESS=1 npm run karma
  - npm run build
branches:
  except:
    - /.*-wip$/
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in travis-ci.org
  keep-history: true
  on:
    branch: master
